spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Rajeswari525/microservices-config.git"
          default-label: "main"
          timeout : 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "file:///C:/Users/91910/Desktop/raji/Microservices/config"
          #search-locations: "classpath:/config"

encrypt:
  key: "rc0F6Bjvm5ebqN9aDgzBKHehYLDlyazF"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"